"""Create initial schema

Revision ID: 2a96046c1a7c
Revises: 
Create Date: 2026-08-30 23:52:38.292210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a96046c1a7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=20), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('is_unavailable', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_duration_seconds'), 'videos', ['duration_seconds'], unique=False)
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_collection_name')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_tag_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('user_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('is_watch_later', sa.Boolean(), nullable=False),
    sa.Column('user_category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_videos_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_user_videos_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_videos')),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video')
    )
    op.create_index(op.f('ix_user_videos_added_at'), 'user_videos', ['added_at'], unique=False)
    op.create_index(op.f('ix_user_videos_is_favourite'), 'user_videos', ['is_favourite'], unique=False)
    op.create_index(op.f('ix_user_videos_is_watch_later'), 'user_videos', ['is_watch_later'], unique=False)
    op.create_index(op.f('ix_user_videos_user_id'), 'user_videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_videos_video_id'), 'user_videos', ['video_id'], unique=False)
    op.create_table('collection_videos',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_video_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_videos_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_video_id'], ['user_videos.id'], name=op.f('fk_collection_videos_user_video_id_user_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'user_video_id', name=op.f('pk_collection_videos'))
    )
    op.create_table('timestamp_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_video_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_video_id'], ['user_videos.id'], name=op.f('fk_timestamp_notes_user_video_id_user_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timestamp_notes'))
    )
    op.create_index(op.f('ix_timestamp_notes_user_video_id'), 'timestamp_notes', ['user_video_id'], unique=False)
    op.create_table('user_video_tags',
    sa.Column('user_video_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_user_video_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_video_id'], ['user_videos.id'], name=op.f('fk_user_video_tags_user_video_id_user_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_video_id', 'tag_id', name=op.f('pk_user_video_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_video_tags')
    op.drop_index(op.f('ix_timestamp_notes_user_video_id'), table_name='timestamp_notes')
    op.drop_table('timestamp_notes')
    op.drop_table('collection_videos')
    op.drop_index(op.f('ix_user_videos_video_id'), table_name='user_videos')
    op.drop_index(op.f('ix_user_videos_user_id'), table_name='user_videos')
    op.drop_index(op.f('ix_user_videos_is_watch_later'), table_name='user_videos')
    op.drop_index(op.f('ix_user_videos_is_favourite'), table_name='user_videos')
    op.drop_index(op.f('ix_user_videos_added_at'), table_name='user_videos')
    op.drop_table('user_videos')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_duration_seconds'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
