from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from typing import Any, cast

import chromadb
from chromadb.api.models.Collection import Collection

from app.embeddings.embedding_schema import EmbeddingBatch
from app.vectorstores.base_vector_store import BaseVectorStore
from app.vectorstores.vector_store_config import VectorStoreConfig
from app.vectorstores.vector_store_schema import (
    SearchResult,
    SearchResults,
)


class ChromaVectorStore(BaseVectorStore):
    """
    Vector store implementation backed by ChromaDB.

    This class stores embeddings that were already generated by our own
    embedding layer. Chroma does not create embeddings inside this class.
    """

    def __init__(self, config: VectorStoreConfig) -> None:
        self._config = config

        self._config.persist_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        self._client = chromadb.PersistentClient(
            path=str(self._config.persist_directory),
        )

        self._collection = self._create_or_load_collection()

    @property
    def config(self) -> VectorStoreConfig:
        return self._config

    @property
    def collection(self) -> Collection:
        return self._collection

    def _create_or_load_collection(self) -> Collection:
        """
        Return the configured collection.

        embedding_function=None is important because embeddings are generated
        by SentenceTransformerEmbedder before they reach Chroma.
        """

        return self._client.get_or_create_collection(
            name=self.config.collection_name,
            embedding_function=None,
            configuration={
                "hnsw": {
                    "space": self.config.distance_metric,
                }
            },
        )

    def upsert(self, batch: EmbeddingBatch) -> int:
        """
        Insert or update an embedding batch.

        Existing records with the same IDs are updated.
        New IDs are inserted.
        """

        if batch.is_empty:
            return 0

        self._validate_batch_dimension(batch)

        metadatas = [self._prepare_metadata(item) for item in batch.metadata]

        self.collection.upsert(
            ids=list(batch.ids),
            embeddings=cast(
                Any,
                [list(vector) for vector in batch.vectors],
            ),
            documents=list(batch.texts),
            metadatas=cast(Any, metadatas),
        )

        return len(batch)

    def search(
        self,
        query_vector: Sequence[float],
        *,
        top_k: int = 5,
        query: str | None = None,
        where: Mapping[str, Any] | None = None,
    ) -> SearchResults:
        """
        Search the collection using one query vector.
        """

        prepared_vector = self._prepare_query_vector(query_vector)

        if top_k <= 0:
            raise ValueError("top_k must be greater than zero.")

        prepared_query = self._prepare_optional_query(query)
        prepared_where = self._prepare_where(where)

        collection_size = self.count()

        if collection_size == 0:
            return SearchResults(
                query=prepared_query,
                results=(),
                collection_name=self.config.collection_name,
            )

        number_of_results = min(top_k, collection_size)

        query_arguments: dict[str, Any] = {
            "query_embeddings": [prepared_vector],
            "n_results": number_of_results,
            "include": [
                "documents",
                "metadatas",
                "distances",
            ],
        }

        if prepared_where is not None:
            query_arguments["where"] = prepared_where

        raw_results = self.collection.query(**query_arguments)

        return self._convert_search_results(
            raw_results=raw_results,
            query=prepared_query,
        )

    def delete(self, ids: Sequence[str]) -> int:
        """
        Delete records using their IDs.
        """

        prepared_ids = self._prepare_ids(ids)

        if not prepared_ids:
            return 0

        self.collection.delete(ids=prepared_ids)

        return len(prepared_ids)

    def count(self) -> int:
        """
        Return the collection record count.
        """

        return self.collection.count()

    def get_by_ids(
        self,
        ids: Sequence[str],
    ) -> list[dict[str, Any]]:
        """
        Retrieve records directly without similarity search.
        """

        prepared_ids = self._prepare_ids(ids)

        if not prepared_ids:
            return []

        result = self.collection.get(
            ids=prepared_ids,
            include=[
                "documents",
                "metadatas",
            ],
        )

        result_ids = result.get("ids") or []
        documents = result.get("documents") or []
        metadatas = result.get("metadatas") or []

        records: list[dict[str, Any]] = []

        for identifier, document, metadata in zip(
            result_ids,
            documents,
            metadatas,
        ):
            records.append(
                {
                    "id": identifier,
                    "document": document,
                    "metadata": metadata or {},
                }
            )

        return records

    def _validate_batch_dimension(
        self,
        batch: EmbeddingBatch,
    ) -> None:
        """
        Check whether the embedding batch has the expected dimension.
        """

        expected = self.config.expected_dimension

        if expected is None:
            return

        if batch.dimension != expected:
            raise ValueError(
                f"Embedding batch dimension is {batch.dimension}, "
                f"but the vector store expects {expected}."
            )

    def _prepare_query_vector(
        self,
        query_vector: Sequence[float],
    ) -> list[float]:
        """
        Validate one query vector.
        """

        if isinstance(query_vector, (str, bytes)):
            raise TypeError("Query vector must be a sequence of numbers.")

        if not query_vector:
            raise ValueError("Query vector cannot be empty.")

        prepared: list[float] = []

        for index, value in enumerate(query_vector):
            if not isinstance(value, (int, float)):
                raise TypeError(
                    "Every query vector value must be numeric, "
                    f"but item {index} is {type(value).__name__}."
                )

            float_value = float(value)

            if not math.isfinite(float_value):
                raise ValueError(f"Query vector value at index {index} must be finite.")

            prepared.append(float_value)

        expected = self.config.expected_dimension

        if expected is not None and len(prepared) != expected:
            raise ValueError(
                f"Query vector dimension is {len(prepared)}, but expected {expected}."
            )

        return prepared

    @staticmethod
    def _prepare_ids(ids: Sequence[str]) -> list[str]:
        """
        Validate record IDs.
        """

        if isinstance(ids, (str, bytes)):
            raise TypeError("Record IDs must be a sequence of strings.")

        prepared_ids: list[str] = []

        for index, identifier in enumerate(ids):
            if not isinstance(identifier, str):
                raise TypeError(
                    "Every record ID must be a string, "
                    f"but item {index} is {type(identifier).__name__}."
                )

            prepared = identifier.strip()

            if not prepared:
                raise ValueError(f"Record ID at index {index} cannot be empty.")

            prepared_ids.append(prepared)

        return prepared_ids

    @staticmethod
    def _prepare_metadata(
        metadata: Mapping[str, Any],
    ) -> dict[str, str | int | float | bool]:
        """
        Convert metadata into Chroma-compatible primitive values.

        Unsupported values are converted to strings.
        None values are removed.
        """

        prepared: dict[str, str | int | float | bool] = {}

        for key, value in metadata.items():
            if value is None:
                continue

            normalized_key = str(key)

            if isinstance(value, bool):
                prepared[normalized_key] = value

            elif isinstance(value, (str, int, float)):
                prepared[normalized_key] = value

            else:
                prepared[normalized_key] = str(value)

        return prepared

    @staticmethod
    def _prepare_optional_query(
        query: str | None,
    ) -> str | None:
        """
        Validate optional original query text.
        """

        if query is None:
            return None

        prepared = query.strip()

        return prepared or None

    @staticmethod
    def _prepare_where(
        where: Mapping[str, Any] | None,
    ) -> dict[str, Any] | None:
        """
        Copy an optional Chroma metadata filter.
        """

        if where is None:
            return None

        return dict(where)

    def _convert_search_results(
        self,
        *,
        raw_results: Mapping[str, Any],
        query: str | None,
    ) -> SearchResults:
        """
        Convert Chroma's nested response into domain SearchResult objects.
        """

        id_batches = raw_results.get("ids") or [[]]
        document_batches = raw_results.get("documents") or [[]]
        metadata_batches = raw_results.get("metadatas") or [[]]
        distance_batches = raw_results.get("distances") or [[]]

        ids = id_batches[0] if id_batches else []
        documents = document_batches[0] if document_batches else []
        metadatas = metadata_batches[0] if metadata_batches else []
        distances = distance_batches[0] if distance_batches else []

        results: list[SearchResult] = []

        for index, identifier in enumerate(ids):
            document = documents[index] if index < len(documents) else ""
            metadata = metadatas[index] if index < len(metadatas) else {}
            distance = distances[index] if index < len(distances) else 0.0

            numeric_distance = float(distance)

            results.append(
                SearchResult(
                    id=str(identifier),
                    document=document or "",
                    metadata=dict(metadata or {}),
                    distance=numeric_distance,
                    score=self._distance_to_score(numeric_distance),
                    rank=index + 1,
                )
            )

        return SearchResults(
            query=query,
            results=tuple(results),
            collection_name=self.config.collection_name,
        )

    def _distance_to_score(self, distance: float) -> float:
        """
        Convert distance into a friendlier similarity score.

        For cosine distance:
            score = 1 - distance

        For other metrics, distance is still returned as the reliable value.
        The score is converted into a bounded convenience value.
        """

        if self.config.distance_metric == "cosine":
            return max(-1.0, min(1.0, 1.0 - distance))

        return 1.0 / (1.0 + max(0.0, distance))
